import { Owner, PG, Floor, Room, Bed, Tenant, RentRecord, Payment, Receipt, NotificationItem, PGSettings } from '@/types';

export const initialOwner: Owner = {
  id: 'owner-1',
  name: 'Rajesh Sharma',
  phone: '+91 98765 43210',
  email: 'rajesh.sharma@sharmapg.com',
  createdAt: '2026-01-15T10:00:00Z',
};

export const initialPG: PG = {
  id: 'pg-1',
  ownerId: 'owner-1',
  name: 'Sharma Luxury PG (Koramangala)',
  address: 'Plot 42, 5th Cross, Koramangala 4th Block, Bengaluru, Karnataka 560034',
  upiId: 'sharmapg@upi',
  contactPhone: '+91 98765 43210',
  numberOfRooms: 6,
  totalBeds: 15,
  createdAt: '2026-01-15T10:00:00Z',
};

export const initialPGs: PG[] = [
  initialPG,
  {
    id: 'pg-2',
    ownerId: 'owner-1',
    name: 'Sharma Student Living (HSR)',
    address: 'Sector 2, 14th Main Rd, HSR Layout, Bengaluru, Karnataka 560102',
    upiId: 'sharmastudent@upi',
    contactPhone: '+91 98765 43210',
    numberOfRooms: 4,
    totalBeds: 8,
    createdAt: '2026-03-01T10:00:00Z',
  },
];

export const initialFloors: Floor[] = [
  { id: 'floor-1', pgId: 'pg-1', floorNumber: 1, name: 'Floor 1' },
  { id: 'floor-2', pgId: 'pg-1', floorNumber: 2, name: 'Floor 2' },
  { id: 'floor-pg2-1', pgId: 'pg-2', floorNumber: 1, name: 'Floor 1' },
  { id: 'floor-pg2-2', pgId: 'pg-2', floorNumber: 2, name: 'Floor 2' },
];

export const initialRooms: Room[] = [
  { id: 'room-101', pgId: 'pg-1', floorId: 'floor-1', roomNumber: '101', capacity: 2, type: 'AC', status: 'ACTIVE' },
  { id: 'room-102', pgId: 'pg-1', floorId: 'floor-1', roomNumber: '102', capacity: 2, type: 'Non-AC', status: 'ACTIVE' },
  { id: 'room-103', pgId: 'pg-1', floorId: 'floor-1', roomNumber: '103', capacity: 3, type: 'AC', status: 'ACTIVE' },
  { id: 'room-201', pgId: 'pg-1', floorId: 'floor-2', roomNumber: '201', capacity: 2, type: 'AC', status: 'ACTIVE' },
  { id: 'room-202', pgId: 'pg-1', floorId: 'floor-2', roomNumber: '202', capacity: 3, type: 'AC', status: 'ACTIVE' },
  { id: 'room-203', pgId: 'pg-1', floorId: 'floor-2', roomNumber: '203', capacity: 3, type: 'AC', status: 'ACTIVE' },
  // PG 2 Rooms
  { id: 'room-301', pgId: 'pg-2', floorId: 'floor-pg2-1', roomNumber: '301', capacity: 2, type: 'AC', status: 'ACTIVE' },
  { id: 'room-302', pgId: 'pg-2', floorId: 'floor-pg2-1', roomNumber: '302', capacity: 2, type: 'Non-AC', status: 'ACTIVE' },
  { id: 'room-401', pgId: 'pg-2', floorId: 'floor-pg2-2', roomNumber: '401', capacity: 2, type: 'AC', status: 'ACTIVE' },
  { id: 'room-402', pgId: 'pg-2', floorId: 'floor-pg2-2', roomNumber: '402', capacity: 2, type: 'Non-AC', status: 'ACTIVE' },
];

export const initialBeds: Bed[] = [
  // Room 101 (2 beds)
  { id: 'bed-101-A', roomId: 'room-101', bedNumber: 'A', tenantId: 'tenant-vikram', status: 'OCCUPIED_PAID' },
  { id: 'bed-101-B', roomId: 'room-101', bedNumber: 'B', tenantId: 'tenant-ananya', status: 'OCCUPIED_PAID' },
  
  // Room 102 (2 beds)
  { id: 'bed-102-A', roomId: 'room-102', bedNumber: 'A', tenantId: undefined, status: 'VACANT' },
  { id: 'bed-102-B', roomId: 'room-102', bedNumber: 'B', tenantId: 'tenant-aman', status: 'OCCUPIED_OVERDUE' },

  // Room 103 (3 beds)
  { id: 'bed-103-A', roomId: 'room-103', bedNumber: 'A', tenantId: 'tenant-kabir', status: 'OCCUPIED_PAID' },
  { id: 'bed-103-B', roomId: 'room-103', bedNumber: 'B', tenantId: 'tenant-manish', status: 'OCCUPIED_PAID' },
  { id: 'bed-103-C', roomId: 'room-103', bedNumber: 'C', tenantId: 'tenant-deepak', status: 'OCCUPIED_OVERDUE' },

  // Room 201 (2 beds)
  { id: 'bed-201-A', roomId: 'room-201', bedNumber: 'A', tenantId: 'tenant-rahul', status: 'OCCUPIED_OVERDUE' },
  { id: 'bed-201-B', roomId: 'room-201', bedNumber: 'B', tenantId: undefined, status: 'VACANT' },

  // Room 202 (3 beds)
  { id: 'bed-202-A', roomId: 'room-202', bedNumber: 'A', tenantId: 'tenant-rohan', status: 'OCCUPIED_DUE_SOON' },
  { id: 'bed-202-B', roomId: 'room-202', bedNumber: 'B', tenantId: 'tenant-sneha', status: 'OCCUPIED_DUE_SOON' },
  { id: 'bed-202-C', roomId: 'room-202', bedNumber: 'C', tenantId: 'tenant-aditya', status: 'OCCUPIED_PAID' },

  // Room 203 (3 beds)
  { id: 'bed-203-A', roomId: 'room-203', bedNumber: 'A', tenantId: 'tenant-priyanshu', status: 'OCCUPIED_PAID' },
  { id: 'bed-203-B', roomId: 'room-203', bedNumber: 'B', tenantId: 'tenant-arjun', status: 'OCCUPIED_PAID' },
  { id: 'bed-203-C', roomId: 'room-203', bedNumber: 'C', tenantId: undefined, status: 'VACANT' },

  // PG 2 Beds (8 beds)
  { id: 'bed-301-A', roomId: 'room-301', bedNumber: 'A', tenantId: 'tenant-karthik', status: 'OCCUPIED_PAID' },
  { id: 'bed-301-B', roomId: 'room-301', bedNumber: 'B', tenantId: 'tenant-pooja', status: 'OCCUPIED_PAID' },
  { id: 'bed-302-A', roomId: 'room-302', bedNumber: 'A', tenantId: 'tenant-nikhil', status: 'OCCUPIED_DUE_SOON' },
  { id: 'bed-302-B', roomId: 'room-302', bedNumber: 'B', tenantId: undefined, status: 'VACANT' },
  { id: 'bed-401-A', roomId: 'room-401', bedNumber: 'A', tenantId: 'tenant-tarun', status: 'OCCUPIED_OVERDUE' },
  { id: 'bed-401-B', roomId: 'room-401', bedNumber: 'B', tenantId: undefined, status: 'VACANT' },
  { id: 'bed-402-A', roomId: 'room-402', bedNumber: 'A', tenantId: undefined, status: 'VACANT' },
  { id: 'bed-402-B', roomId: 'room-402', bedNumber: 'B', tenantId: undefined, status: 'VACANT' },
];

export const initialTenants: Tenant[] = [
  {
    id: 'tenant-priyanshu',
    pgId: 'pg-1',
    name: 'Priyanshu Verma',
    phone: '+91 98450 11223',
    email: 'priyanshu.v@techcorp.com',
    roomId: 'room-203',
    bedId: 'bed-203-A',
    monthlyRent: 8000,
    securityDeposit: 10000,
    depositStatus: 'HELD',
    joiningDate: '2026-06-01',
    dueDateDay: 5,
    status: 'ACTIVE',
    emergencyContact: '+91 98450 99887 (Father)',
    notes: 'Software engineer at FinTech startup',
  },
  {
    id: 'tenant-rahul',
    pgId: 'pg-1',
    name: 'Rahul Mehta',
    phone: '+91 97112 34567',
    email: 'rahul.m@cloudtech.com',
    roomId: 'room-201',
    bedId: 'bed-201-A',
    monthlyRent: 8000,
    securityDeposit: 10000,
    depositStatus: 'HELD',
    joiningDate: '2026-05-15',
    dueDateDay: 5,
    status: 'ACTIVE',
    emergencyContact: '+91 97112 00001 (Brother)',
    notes: 'Usually pays after reminder',
  },
  {
    id: 'tenant-aman',
    pgId: 'pg-1',
    name: 'Aman Sharma',
    phone: '+91 98234 56789',
    email: 'aman.sharma@designhub.io',
    roomId: 'room-102',
    bedId: 'bed-102-B',
    monthlyRent: 7500,
    securityDeposit: 10000,
    depositStatus: 'HELD',
    joiningDate: '2026-07-01',
    dueDateDay: 5,
    status: 'ACTIVE',
    emergencyContact: '+91 98234 11112 (Mother)',
  },
  {
    id: 'tenant-deepak',
    pgId: 'pg-1',
    name: 'Deepak Joshi',
    phone: '+91 99887 65432',
    email: 'deepak.j@datasys.in',
    roomId: 'room-103',
    bedId: 'bed-103-C',
    monthlyRent: 8000,
    securityDeposit: 10000,
    depositStatus: 'HELD',
    joiningDate: '2026-04-10',
    dueDateDay: 5,
    status: 'ACTIVE',
    emergencyContact: '+91 99887 00000 (Father)',
  },
  {
    id: 'tenant-rohan',
    pgId: 'pg-1',
    name: 'Rohan Gupta',
    phone: '+91 98761 23450',
    email: 'rohan.gupta@marketingpro.in',
    roomId: 'room-202',
    bedId: 'bed-202-A',
    monthlyRent: 8000,
    securityDeposit: 10000,
    depositStatus: 'HELD',
    joiningDate: '2026-06-15',
    dueDateDay: 10,
    status: 'ACTIVE',
  },
  {
    id: 'tenant-sneha',
    pgId: 'pg-1',
    name: 'Sneha Rao',
    phone: '+91 91234 56780',
    email: 'sneha.rao@biotech.com',
    roomId: 'room-202',
    bedId: 'bed-202-B',
    monthlyRent: 8500,
    securityDeposit: 12000,
    depositStatus: 'HELD',
    joiningDate: '2026-03-01',
    dueDateDay: 10,
    status: 'ACTIVE',
  },
  {
    id: 'tenant-vikram',
    pgId: 'pg-1',
    name: 'Vikram Singh',
    phone: '+91 93456 78901',
    email: 'vikram.singh@logistics.com',
    roomId: 'room-101',
    bedId: 'bed-101-A',
    monthlyRent: 7500,
    securityDeposit: 9000,
    depositStatus: 'HELD',
    joiningDate: '2026-02-10',
    dueDateDay: 5,
    status: 'ACTIVE',
  },
  {
    id: 'tenant-ananya',
    pgId: 'pg-1',
    name: 'Ananya Iyer',
    phone: '+91 94567 89012',
    email: 'ananya.iyer@edutech.org',
    roomId: 'room-101',
    bedId: 'bed-101-B',
    monthlyRent: 7500,
    securityDeposit: 9000,
    depositStatus: 'HELD',
    joiningDate: '2026-01-20',
    dueDateDay: 5,
    status: 'ACTIVE',
  },
  {
    id: 'tenant-kabir',
    pgId: 'pg-1',
    name: 'Kabir Khan',
    phone: '+91 95678 90123',
    email: 'kabir.k@motionmedia.in',
    roomId: 'room-103',
    bedId: 'bed-103-A',
    monthlyRent: 8000,
    securityDeposit: 10000,
    depositStatus: 'HELD',
    joiningDate: '2026-05-01',
    dueDateDay: 5,
    status: 'ACTIVE',
  },
  {
    id: 'tenant-manish',
    pgId: 'pg-1',
    name: 'Manish Pandey',
    phone: '+91 96789 01234',
    email: 'manish.p@retailchain.com',
    roomId: 'room-103',
    bedId: 'bed-103-B',
    monthlyRent: 8000,
    securityDeposit: 10000,
    depositStatus: 'HELD',
    joiningDate: '2026-04-01',
    dueDateDay: 5,
    status: 'ACTIVE',
  },
  {
    id: 'tenant-aditya',
    pgId: 'pg-1',
    name: 'Aditya Kulkarni',
    phone: '+91 97890 12345',
    email: 'aditya.k@finserve.com',
    roomId: 'room-202',
    bedId: 'bed-202-C',
    monthlyRent: 8000,
    securityDeposit: 10000,
    depositStatus: 'HELD',
    joiningDate: '2026-05-10',
    dueDateDay: 5,
    status: 'ACTIVE',
  },
  {
    id: 'tenant-arjun',
    pgId: 'pg-1',
    name: 'Arjun Nair',
    phone: '+91 98901 23456',
    email: 'arjun.nair@aerospace.org',
    roomId: 'room-203',
    bedId: 'bed-203-B',
    monthlyRent: 8000,
    securityDeposit: 10000,
    depositStatus: 'HELD',
    joiningDate: '2026-06-10',
    dueDateDay: 5,
    status: 'ACTIVE',
  },
  // PG 2 Students (HSR Layout)
  {
    id: 'tenant-karthik',
    pgId: 'pg-2',
    name: 'Karthik Reddy',
    phone: '+91 98888 12345',
    email: 'karthik.r@college.edu.in',
    roomId: 'room-301',
    bedId: 'bed-301-A',
    monthlyRent: 7000,
    securityDeposit: 8000,
    depositStatus: 'HELD',
    joiningDate: '2026-07-01',
    dueDateDay: 5,
    status: 'ACTIVE',
    notes: 'Computer Science student',
  },
  {
    id: 'tenant-pooja',
    pgId: 'pg-2',
    name: 'Pooja Hegde',
    phone: '+91 97777 23456',
    email: 'pooja.h@university.ac.in',
    roomId: 'room-301',
    bedId: 'bed-301-B',
    monthlyRent: 7000,
    securityDeposit: 8000,
    depositStatus: 'HELD',
    joiningDate: '2026-07-15',
    dueDateDay: 5,
    status: 'ACTIVE',
    notes: 'Biotechnology student',
  },
  {
    id: 'tenant-nikhil',
    pgId: 'pg-2',
    name: 'Nikhil Gowda',
    phone: '+91 96666 34567',
    email: 'nikhil.g@institute.org',
    roomId: 'room-302',
    bedId: 'bed-302-A',
    monthlyRent: 7200,
    securityDeposit: 8000,
    depositStatus: 'HELD',
    joiningDate: '2026-08-01',
    dueDateDay: 10,
    status: 'ACTIVE',
    notes: 'Mechanical Engineering student',
  },
  {
    id: 'tenant-tarun',
    pgId: 'pg-2',
    name: 'Tarun Nair',
    phone: '+91 95555 45678',
    email: 'tarun.n@designschool.in',
    roomId: 'room-401',
    bedId: 'bed-401-A',
    monthlyRent: 7500,
    securityDeposit: 9000,
    depositStatus: 'HELD',
    joiningDate: '2026-06-01',
    dueDateDay: 5,
    status: 'ACTIVE',
    notes: 'Design student',
  },
];

export const initialRentRecords: RentRecord[] = [
  // Current Month: October 2026
  // PG 2 Records
  {
    id: 'rent-karthik-oct',
    pgId: 'pg-2',
    tenantId: 'tenant-karthik',
    month: 'October 2026',
    yearMonth: '2026-10',
    amount: 7000,
    dueDate: '2026-10-05',
    status: 'PAID',
    daysOverdue: 0,
    paymentId: 'pay-karthik-oct',
    createdAt: '2026-10-01T00:00:00Z',
  },
  {
    id: 'rent-pooja-oct',
    pgId: 'pg-2',
    tenantId: 'tenant-pooja',
    month: 'October 2026',
    yearMonth: '2026-10',
    amount: 7000,
    dueDate: '2026-10-05',
    status: 'PAID',
    daysOverdue: 0,
    paymentId: 'pay-pooja-oct',
    createdAt: '2026-10-01T00:00:00Z',
  },
  {
    id: 'rent-nikhil-oct',
    pgId: 'pg-2',
    tenantId: 'tenant-nikhil',
    month: 'October 2026',
    yearMonth: '2026-10',
    amount: 7200,
    dueDate: '2026-10-10',
    status: 'PENDING',
    daysOverdue: 0,
    createdAt: '2026-10-01T00:00:00Z',
  },
  {
    id: 'rent-tarun-oct',
    pgId: 'pg-2',
    tenantId: 'tenant-tarun',
    month: 'October 2026',
    yearMonth: '2026-10',
    amount: 7500,
    dueDate: '2026-10-05',
    status: 'OVERDUE',
    daysOverdue: 2,
    createdAt: '2026-10-01T00:00:00Z',
  },
  {
    id: 'rent-priyanshu-oct',
    pgId: 'pg-1',
    tenantId: 'tenant-priyanshu',
    month: 'October 2026',
    yearMonth: '2026-10',
    amount: 8000,
    dueDate: '2026-10-05',
    status: 'PAID',
    daysOverdue: 0,
    paymentId: 'pay-priyanshu-oct',
    createdAt: '2026-10-01T00:00:00Z',
  },
  {
    id: 'rent-rahul-oct',
    pgId: 'pg-1',
    tenantId: 'tenant-rahul',
    month: 'October 2026',
    yearMonth: '2026-10',
    amount: 8000,
    dueDate: '2026-10-05',
    status: 'OVERDUE',
    daysOverdue: 3,
    createdAt: '2026-10-01T00:00:00Z',
  },
  {
    id: 'rent-aman-oct',
    pgId: 'pg-1',
    tenantId: 'tenant-aman',
    month: 'October 2026',
    yearMonth: '2026-10',
    amount: 7500,
    dueDate: '2026-10-05',
    status: 'OVERDUE',
    daysOverdue: 2,
    createdAt: '2026-10-01T00:00:00Z',
  },
  {
    id: 'rent-deepak-oct',
    pgId: 'pg-1',
    tenantId: 'tenant-deepak',
    month: 'October 2026',
    yearMonth: '2026-10',
    amount: 8000,
    dueDate: '2026-10-05',
    status: 'OVERDUE',
    daysOverdue: 1,
    createdAt: '2026-10-01T00:00:00Z',
  },
  {
    id: 'rent-rohan-oct',
    pgId: 'pg-1',
    tenantId: 'tenant-rohan',
    month: 'October 2026',
    yearMonth: '2026-10',
    amount: 8000,
    dueDate: '2026-10-10',
    status: 'PENDING',
    daysOverdue: 0,
    createdAt: '2026-10-01T00:00:00Z',
  },
  {
    id: 'rent-sneha-oct',
    pgId: 'pg-1',
    tenantId: 'tenant-sneha',
    month: 'October 2026',
    yearMonth: '2026-10',
    amount: 8500,
    dueDate: '2026-10-10',
    status: 'PENDING',
    daysOverdue: 0,
    createdAt: '2026-10-01T00:00:00Z',
  },
  {
    id: 'rent-vikram-oct',
    pgId: 'pg-1',
    tenantId: 'tenant-vikram',
    month: 'October 2026',
    yearMonth: '2026-10',
    amount: 7500,
    dueDate: '2026-10-05',
    status: 'PAID',
    daysOverdue: 0,
    paymentId: 'pay-vikram-oct',
    createdAt: '2026-10-01T00:00:00Z',
  },
  {
    id: 'rent-ananya-oct',
    pgId: 'pg-1',
    tenantId: 'tenant-ananya',
    month: 'October 2026',
    yearMonth: '2026-10',
    amount: 7500,
    dueDate: '2026-10-05',
    status: 'PAID',
    daysOverdue: 0,
    paymentId: 'pay-ananya-oct',
    createdAt: '2026-10-01T00:00:00Z',
  },
  {
    id: 'rent-kabir-oct',
    pgId: 'pg-1',
    tenantId: 'tenant-kabir',
    month: 'October 2026',
    yearMonth: '2026-10',
    amount: 8000,
    dueDate: '2026-10-05',
    status: 'PAID',
    daysOverdue: 0,
    paymentId: 'pay-kabir-oct',
    createdAt: '2026-10-01T00:00:00Z',
  },
  {
    id: 'rent-manish-oct',
    pgId: 'pg-1',
    tenantId: 'tenant-manish',
    month: 'October 2026',
    yearMonth: '2026-10',
    amount: 8000,
    dueDate: '2026-10-05',
    status: 'PAID',
    daysOverdue: 0,
    paymentId: 'pay-manish-oct',
    createdAt: '2026-10-01T00:00:00Z',
  },
  {
    id: 'rent-aditya-oct',
    pgId: 'pg-1',
    tenantId: 'tenant-aditya',
    month: 'October 2026',
    yearMonth: '2026-10',
    amount: 8000,
    dueDate: '2026-10-05',
    status: 'PAID',
    daysOverdue: 0,
    paymentId: 'pay-aditya-oct',
    createdAt: '2026-10-01T00:00:00Z',
  },
  {
    id: 'rent-arjun-oct',
    pgId: 'pg-1',
    tenantId: 'tenant-arjun',
    month: 'October 2026',
    yearMonth: '2026-10',
    amount: 8000,
    dueDate: '2026-10-05',
    status: 'PAID',
    daysOverdue: 0,
    paymentId: 'pay-arjun-oct',
    createdAt: '2026-10-01T00:00:00Z',
  },
];

export const initialPayments: Payment[] = [
  {
    id: 'pay-priyanshu-oct',
    pgId: 'pg-1',
    tenantId: 'tenant-priyanshu',
    rentRecordId: 'rent-priyanshu-oct',
    amount: 8000,
    paymentDate: '2026-10-05T14:32:00Z',
    transactionId: 'TXN-UPI-98214401',
    paymentMethod: 'UPI',
    providerReference: 'razorpay_pay_982144',
    status: 'SUCCESS',
  },
  {
    id: 'pay-vikram-oct',
    pgId: 'pg-1',
    tenantId: 'tenant-vikram',
    rentRecordId: 'rent-vikram-oct',
    amount: 7500,
    paymentDate: '2026-10-04T18:12:00Z',
    transactionId: 'TXN-UPI-98110023',
    paymentMethod: 'UPI',
    providerReference: 'razorpay_pay_981100',
    status: 'SUCCESS',
  },
  {
    id: 'pay-ananya-oct',
    pgId: 'pg-1',
    tenantId: 'tenant-ananya',
    rentRecordId: 'rent-ananya-oct',
    amount: 7500,
    paymentDate: '2026-10-05T09:45:00Z',
    transactionId: 'TXN-NET-54002911',
    paymentMethod: 'NET_BANKING',
    providerReference: 'hdfc_net_540029',
    status: 'SUCCESS',
  },
  {
    id: 'pay-kabir-oct',
    pgId: 'pg-1',
    tenantId: 'tenant-kabir',
    rentRecordId: 'rent-kabir-oct',
    amount: 8000,
    paymentDate: '2026-10-03T11:20:00Z',
    transactionId: 'TXN-UPI-97992014',
    paymentMethod: 'UPI',
    providerReference: 'razorpay_pay_979920',
    status: 'SUCCESS',
  },
  {
    id: 'pay-manish-oct',
    pgId: 'pg-1',
    tenantId: 'tenant-manish',
    rentRecordId: 'rent-manish-oct',
    amount: 8000,
    paymentDate: '2026-10-05T16:04:00Z',
    transactionId: 'TXN-UPI-98299104',
    paymentMethod: 'UPI',
    providerReference: 'razorpay_pay_982991',
    status: 'SUCCESS',
  },
  {
    id: 'pay-aditya-oct',
    pgId: 'pg-1',
    tenantId: 'tenant-aditya',
    rentRecordId: 'rent-aditya-oct',
    amount: 8000,
    paymentDate: '2026-10-02T20:10:00Z',
    transactionId: 'TXN-UPI-97811045',
    paymentMethod: 'UPI',
    providerReference: 'razorpay_pay_978110',
    status: 'SUCCESS',
  },
  {
    id: 'pay-arjun-oct',
    pgId: 'pg-1',
    tenantId: 'tenant-arjun',
    rentRecordId: 'rent-arjun-oct',
    amount: 8000,
    paymentDate: '2026-10-05T13:15:00Z',
    transactionId: 'TXN-UPI-98244190',
    paymentMethod: 'UPI',
    providerReference: 'razorpay_pay_982441',
    status: 'SUCCESS',
  },
];

export const initialReceipts: Receipt[] = [
  {
    id: 'rec-priyanshu-oct',
    receiptNumber: 'SHR-202610-001',
    paymentId: 'pay-priyanshu-oct',
    tenantId: 'tenant-priyanshu',
    rentRecordId: 'rent-priyanshu-oct',
    amount: 8000,
    month: 'October 2026',
    generatedAt: '2026-10-05T14:32:05Z',
  },
  {
    id: 'rec-vikram-oct',
    receiptNumber: 'SHR-202610-002',
    paymentId: 'pay-vikram-oct',
    tenantId: 'tenant-vikram',
    rentRecordId: 'rent-vikram-oct',
    amount: 7500,
    month: 'October 2026',
    generatedAt: '2026-10-04T18:12:05Z',
  },
  {
    id: 'rec-ananya-oct',
    receiptNumber: 'SHR-202610-003',
    paymentId: 'pay-ananya-oct',
    tenantId: 'tenant-ananya',
    rentRecordId: 'rent-ananya-oct',
    amount: 7500,
    month: 'October 2026',
    generatedAt: '2026-10-05T09:45:05Z',
  },
  {
    id: 'rec-kabir-oct',
    receiptNumber: 'SHR-202610-004',
    paymentId: 'pay-kabir-oct',
    tenantId: 'tenant-kabir',
    rentRecordId: 'rent-kabir-oct',
    amount: 8000,
    month: 'October 2026',
    generatedAt: '2026-10-03T11:20:05Z',
  },
  {
    id: 'rec-manish-oct',
    receiptNumber: 'SHR-202610-005',
    paymentId: 'pay-manish-oct',
    tenantId: 'tenant-manish',
    rentRecordId: 'rent-manish-oct',
    amount: 8000,
    month: 'October 2026',
    generatedAt: '2026-10-05T16:04:05Z',
  },
  {
    id: 'rec-aditya-oct',
    receiptNumber: 'SHR-202610-006',
    paymentId: 'pay-aditya-oct',
    tenantId: 'tenant-aditya',
    rentRecordId: 'rent-aditya-oct',
    amount: 8000,
    month: 'October 2026',
    generatedAt: '2026-10-02T20:10:05Z',
  },
  {
    id: 'rec-arjun-oct',
    receiptNumber: 'SHR-202610-007',
    paymentId: 'pay-arjun-oct',
    tenantId: 'tenant-arjun',
    rentRecordId: 'rent-arjun-oct',
    amount: 8000,
    month: 'October 2026',
    generatedAt: '2026-10-05T13:15:05Z',
  },
];

export const initialNotifications: NotificationItem[] = [
  {
    id: 'notif-1',
    tenantId: 'tenant-rahul',
    tenantName: 'Rahul Mehta',
    phone: '+91 97112 34567',
    type: 'REMINDER_OVERDUE_3D',
    channel: 'WHATSAPP',
    message: 'Hi Rahul, your rent of ₹8,000 for October is overdue by 3 days. Please pay immediately using: https://sharmapg.com/pay/rent-rahul-oct',
    scheduledDate: '2026-10-08T09:00:00Z',
    sentDate: '2026-10-08T09:01:15Z',
    status: 'SENT',
    paymentLink: 'https://sharmapg.com/pay/rent-rahul-oct',
  },
  {
    id: 'notif-2',
    tenantId: 'tenant-aman',
    tenantName: 'Aman Sharma',
    phone: '+91 98234 56789',
    type: 'REMINDER_OVERDUE_1D',
    channel: 'WHATSAPP',
    message: 'Hi Aman, your rent of ₹7,500 for October is overdue by 2 days. Pay here: https://sharmapg.com/pay/rent-aman-oct',
    scheduledDate: '2026-10-07T09:00:00Z',
    sentDate: '2026-10-07T09:00:45Z',
    status: 'SENT',
    paymentLink: 'https://sharmapg.com/pay/rent-aman-oct',
  },
  {
    id: 'notif-3',
    tenantId: 'tenant-priyanshu',
    tenantName: 'Priyanshu Verma',
    phone: '+91 98450 11223',
    type: 'PAYMENT_RECEIVED',
    channel: 'WHATSAPP',
    message: 'Hi Priyanshu, we received your payment of ₹8,000 for October Rent. Receipt SHR-202610-001 has been generated. Thank you!',
    scheduledDate: '2026-10-05T14:32:10Z',
    sentDate: '2026-10-05T14:32:12Z',
    status: 'SENT',
  }
];

export const initialSettings: PGSettings = {
  autoRemindersEnabled: true,
  defaultDueDay: 5,
  upiId: 'sharmapg@upi',
  upiName: 'Sharma Luxury PG',
  rules: [
    {
      id: 'rule-1',
      key: 'before_3d',
      title: '3 Days Before Due Date',
      description: 'Gentle advance reminder with upcoming rent amount & due date',
      enabled: true,
      daysOffset: -3,
    },
    {
      id: 'rule-2',
      key: 'before_1d',
      title: '1 Day Before Due Date',
      description: '"Rent due tomorrow" reminder with direct UPI payment link',
      enabled: true,
      daysOffset: -1,
    },
    {
      id: 'rule-3',
      key: 'due_today',
      title: 'On Due Date',
      description: '"Your rent is due today" prompt with payment link',
      enabled: true,
      daysOffset: 0,
    },
    {
      id: 'rule-4',
      key: 'after_1d',
      title: '1 Day After Due Date (Overdue)',
      description: 'First overdue notice: "Your rent is overdue by 1 day"',
      enabled: true,
      daysOffset: 1,
    },
    {
      id: 'rule-5',
      key: 'after_3d',
      title: '3 Days After Due Date (Urgent)',
      description: 'Escalation notice: "Your rent is overdue by 3 days"',
      enabled: true,
      daysOffset: 3,
    },
  ],
};
